services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    container_name: backend
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app  
      - /usr/src/app/node_modules

volumes:
  mongodb_data: